// Autogenerated by Frugal Compiler (1.0.9)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package stingy

import (
        "github.com/Workiva/frugal/lib/go"
	"bytes"
	"fmt"
	"sync"
	"time"

	"git.apache.org/thrift.git/lib/go/thrift"
	"github.com/danielrowles-wf/cheapskate/gen-go/workiva_frugal_api"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

type FStingyService interface {
	workiva_frugal_api.FBaseService

	GetQuote(ctx *frugal.FContext) (r string, err error)
}

type FStingyServiceClient struct {
	*workiva_frugal_api.FBaseServiceClient
	transport       frugal.FTransport
	protocolFactory *frugal.FProtocolFactory
	oprot           *frugal.FProtocol
	mu              sync.Mutex
}

func NewFStingyServiceClient(t frugal.FTransport, p *frugal.FProtocolFactory) *FStingyServiceClient {
	t.SetRegistry(frugal.NewFClientRegistry())
	return &FStingyServiceClient{
		FBaseServiceClient: workiva_frugal_api.NewFBaseServiceClient(t, p),
		transport:          t,
		protocolFactory:    p,
		oprot:              p.GetProtocol(t),
	}
}

func (f *FStingyServiceClient) GetQuote(ctx *frugal.FContext) (r string, err error) {
	errorC := make(chan error, 1)
	resultC := make(chan string, 1)
	if err = f.transport.Register(ctx, f.recvGetQuoteHandler(ctx, resultC, errorC)); err != nil {
		return
	}
	defer f.transport.Unregister(ctx)
	f.mu.Lock()
	if err = f.oprot.WriteRequestHeader(ctx); err != nil {
		f.mu.Unlock()
		return
	}
	if err = f.oprot.WriteMessageBegin("getQuote", thrift.CALL, 0); err != nil {
		f.mu.Unlock()
		return
	}
	args := StingyServiceGetQuoteArgs{}
	if err = args.Write(f.oprot); err != nil {
		f.mu.Unlock()
		return
	}
	if err = f.oprot.WriteMessageEnd(); err != nil {
		f.mu.Unlock()
		return
	}
	if err = f.oprot.Flush(); err != nil {
		f.mu.Unlock()
		return
	}
	f.mu.Unlock()

	select {
	case err = <-errorC:
	case r = <-resultC:
	case <-time.After(ctx.Timeout()):
		err = frugal.ErrTimeout
	case <-f.transport.Closed():
		err = frugal.ErrTransportClosed
	}
	return
}

func (f *FStingyServiceClient) recvGetQuoteHandler(ctx *frugal.FContext, resultC chan<- string, errorC chan<- error) frugal.FAsyncCallback {
	return func(tr thrift.TTransport) error {
		iprot := f.protocolFactory.GetProtocol(tr)
		if err := iprot.ReadResponseHeader(ctx); err != nil {
			errorC <- err
			return err
		}
		method, mTypeId, _, err := iprot.ReadMessageBegin()
		if err != nil {
			errorC <- err
			return err
		}
		if method != "getQuote" {
			err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "getQuote failed: wrong method name")
			errorC <- err
			return err
		}
		if mTypeId == thrift.EXCEPTION {
			error0 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
			var error1 thrift.TApplicationException
			error1, err = error0.Read(iprot)
			if err != nil {
				errorC <- err
				return err
			}
			if err = iprot.ReadMessageEnd(); err != nil {
				errorC <- err
				return err
			}
			if error1.TypeId() == frugal.RESPONSE_TOO_LARGE {
				err = thrift.NewTTransportException(frugal.RESPONSE_TOO_LARGE, "response too large for transport")
				errorC <- err
				return nil
			}
			err = error1
			errorC <- err
			return err
		}
		if mTypeId != thrift.REPLY {
			err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "getQuote failed: invalid message type")
			errorC <- err
			return err
		}
		result := StingyServiceGetQuoteResult{}
		if err = result.Read(iprot); err != nil {
			errorC <- err
			return err
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			errorC <- err
			return err
		}
		resultC <- result.GetSuccess()
		return nil
	}
}

type FStingyServiceProcessor struct {
	*workiva_frugal_api.FBaseServiceProcessor
}

func NewFStingyServiceProcessor(handler FStingyService) *FStingyServiceProcessor {
	p := &FStingyServiceProcessor{
		workiva_frugal_api.NewFBaseServiceProcessor(handler),
	}
	p.AddToProcessorMap("getQuote", &stingyserviceFGetQuote{handler: handler, writeMu: p.GetWriteMutex()})
	return p
}

type stingyserviceFGetQuote struct {
	handler FStingyService
	writeMu *sync.Mutex
}

func (p *stingyserviceFGetQuote) Process(ctx *frugal.FContext, iprot, oprot *frugal.FProtocol) error {
	args := StingyServiceGetQuoteArgs{}
	var err error
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		p.writeMu.Lock()
		stingyserviceWriteApplicationError(ctx, oprot, thrift.PROTOCOL_ERROR, "getQuote", err.Error())
		p.writeMu.Unlock()
		return err
	}

	iprot.ReadMessageEnd()
	result := StingyServiceGetQuoteResult{}
	var err2 error
	var retval string
	if retval, err2 = p.handler.GetQuote(ctx); err2 != nil {
		p.writeMu.Lock()
		stingyserviceWriteApplicationError(ctx, oprot, thrift.INTERNAL_ERROR, "getQuote", "Internal error processing getQuote: "+err2.Error())
		p.writeMu.Unlock()
		return err2
	} else {
		result.Success = &retval
	}
	p.writeMu.Lock()
	defer p.writeMu.Unlock()
	if err2 = oprot.WriteResponseHeader(ctx); err2 != nil {
		if err2 == frugal.ErrTooLarge {
			stingyserviceWriteApplicationError(ctx, oprot, frugal.RESPONSE_TOO_LARGE, "getQuote", "response too large: "+err2.Error())
			return nil
		}
		err = err2
	}
	if err2 = oprot.WriteMessageBegin("getQuote", thrift.REPLY, 0); err2 != nil {
		if err2 == frugal.ErrTooLarge {
			stingyserviceWriteApplicationError(ctx, oprot, frugal.RESPONSE_TOO_LARGE, "getQuote", "response too large: "+err2.Error())
			return nil
		}
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		if err2 == frugal.ErrTooLarge {
			stingyserviceWriteApplicationError(ctx, oprot, frugal.RESPONSE_TOO_LARGE, "getQuote", "response too large: "+err2.Error())
			return nil
		}
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		if err2 == frugal.ErrTooLarge {
			stingyserviceWriteApplicationError(ctx, oprot, frugal.RESPONSE_TOO_LARGE, "getQuote", "response too large: "+err2.Error())
			return nil
		}
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		if err2 == frugal.ErrTooLarge {
			stingyserviceWriteApplicationError(ctx, oprot, frugal.RESPONSE_TOO_LARGE, "getQuote", "response too large: "+err2.Error())
			return nil
		}
		err = err2
	}
	return err
}

func stingyserviceWriteApplicationError(ctx *frugal.FContext, oprot *frugal.FProtocol, type_ int32, method, message string) {
	x := thrift.NewTApplicationException(type_, message)
	oprot.WriteResponseHeader(ctx)
	oprot.WriteMessageBegin(method, thrift.EXCEPTION, 0)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush()
}
